#**Theoretical Question:**

#**Q1.** Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

#Purpose of NumPy in Scientific Computing and Data Analysis:
##NumPy (Numerical Python) is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with an extensive collection of high-level mathematical functions to operate on these arrays. It is fundamental to scientific computing and data analysis because it offers performance and functionality enhancements over Python's native lists and loops.

#**1.Efficient Array Operations:**
#**Speed:** NumPy arrays are implemented in C, making them significantly faster than Python lists for numerical computations. This performance boost is crucial for handling large datasets efficiently.
#**Vectorization:** NumPy allows you to perform operations on entire arrays at once, rather than iterating over individual elements. This vectorization leads to significant speed improvements compared to using loops in pure Python.
#**Memory Efficiency:** NumPy arrays are more memory-efficient than Python lists, especially for large datasets.
#**2. Powerful Data Structures:**

#**ndarrays:** The core of NumPy is the ndarray object, which represents a multidimensional array of homogeneous data types. This provides a versatile and efficient way to store and manipulate numerical data.
#**Broadcasting:** NumPy supports broadcasting, which allows operations between arrays of different shapes. For example, you can add a scalar value to an array, or add arrays of different sizes under certain conditions.
#**3. Extensive Functionality:**

#**Linear Algebra:** NumPy provides a wide range of linear algebra functions, including matrix multiplication, eigenvalues, eigenvectors, and more.
#**Random Number Generation:** NumPy includes a powerful random number generator for various statistical distributions.
#**Fourier Transforms:** NumPy offers efficient implementations of Fourier transforms for signal processing and other applications.
#**Shape Manipulation:** NumPy provides functions for reshaping, slicing, and indexing arrays, allowing you to easily manipulate data structures.



#**Q2.** Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

#**np.mean()**

##**Purpose:** Calculates the arithmetic mean (simple average) of an array.
##**Usage:** Primarily used for calculating the average of a set of values where all values have equal weight.
#**np.average()**

##**Purpose:** Calculates the weighted average of an array.
##**Usage:**When there is a set of values where some values are more important or influential than others.
##provide weights to each value in the array to reflect their relative importance.


#**Use np.mean()** for general-purpose averaging without weights.
#**Use np.average()** when weights are involved or when the sum of weights is also needed.







#**Q3.** Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [ ]:
import numpy as np

# 1D Array Example
arr1d = np.array([1, 2, 3, 4, 5])
reversed_arr1d = np.flip(arr1d)
print("Reversed 1D Array:", reversed_arr1d)

# 2D Array Example
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along the first axis (rows)
reversed_rows = np.flip(arr2d, axis=0)
print("Reversed Rows:\n", reversed_rows)

# Reverse along the second axis (columns)
reversed_cols = np.flip(arr2d, axis=1)
print("Reversed Columns:\n", reversed_cols)

# Reverse along both axes
reversed_both = np.flip(arr2d, axis=(0, 1))
print("Reversed Both Axes:\n", reversed_both)

Reversed 1D Array: [5 4 3 2 1]
Reversed Rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed Columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed Both Axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


#**Q4.** How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#Determining Data Type of elements in a  NumPy Array using the `dtype` attribute:


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Data type:", arr.dtype)

arr_float = np.array([1.0, 2.5, 3.14])
print("Data type:", arr_float.dtype)

Data type: int64
Data type: float64


##Importance of Data Types in Memory Management and Performance

#**Memory Efficiency:** Minimizing memory usage and avoiding unnecessary overhead.
#**Performance Optimization:** Achieving faster computation speeds.
#**Data Accuracy:** Ensuring that your data is represented correctly and accurately.

##By selecting the appropriate data type for your arrays, you can significantly improve the performance and efficiency of your numerical computations in Python.


#**Q5.** Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#An `ndarray` is the core data structure in NumPy. It is a multidimensional, homogeneous array of fixed-size items. The elements in an `ndarray` are all of the same data type, and its size is defined at creation.

#**Key Features of `ndarray`**
#1.Multidimensional: Supports arrays of any dimensionality (1D, 2D, 3D, etc.).
#2.Homogeneous: all elements in an `ndarray` must have the same data type (dtype).
#3.Fixed Size: The size of an ndarray is fixed upon creation and cannot be changed.
#4.Highly Efficient:
#Designed for numerical computations with high performance.
#Operations are vectorized, reducing the need for explicit loops.
#5.Memory-Efficient:
#Stores data in contiguous blocks of memory, making access and operations faster compared to Python lists.
#6.Indexing and Slicing:
#Supports advanced indexing and slicing for accessing subsets of data.
#7.Support for Broadcasting:
#Allows arithmetic operations between arrays of different shapes.

#**Differences from Python Lists:**

##**Homogeneity:** Python lists can hold elements of different data types (heterogeneous), while ndarrays must contain elements of the same data type.
##**Performance:** NumPy arrays are generally much faster for numerical operations due to their optimized implementation and vectorization capabilities.
##**Memory Efficiency:** NumPy arrays are often more memory-efficient, especially for large datasets, as they are stored in contiguous blocks of memory.
##**Multidimensionality:** While Python lists can represent multidimensional data using nested lists, ndarrays provide a more natural and efficient way to work with multidimensional data.

#**Q6.** Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#NumPy arrays offer significant performance advantages over Python lists for large-scale numerical operations due to several key factors.

#**Vectorization:**
##NumPy arrays support vectorized operations, allowing computations to be performed on entire arrays without explicit loops.
##Python lists require element-wise operations using loops, which are slower due to Python's dynamic type checking.

#**Memory Efficiency:**
##NumPy arrays store elements in a contiguous block of memory, ensuring faster access and better cache performance.
##Python lists, in contrast, are arrays of pointers to objects, leading to additional memory overhead for the pointers and objects themselves.

#**Optimized Libraries:**
##NumPy is implemented in C and Fortran, which are optimized for numerical operations, avoiding the overhead of Python's interpreted execution.

#Example: Adding two arrays

In [ ]:
import numpy as np
import time

size = 10**6
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
print("Python List Addition:", time.time() - start)

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result_array = arr1 + arr2
print("NumPy Array Addition:", time.time() - start)


Python List Addition: 0.1630702018737793
NumPy Array Addition: 0.006750345230102539


#**Performance Demonstration: Large-Scale Computations**
##**Python List Approach:** You would likely use a loop to iterate over both lists, multiplying corresponding elements and storing the results in a new list. This can be slow, especially for large arrays.
##**NumPy Array Approach:** You can simply use the `*` operator on the NumPy arrays, and the operation will be performed element-wise on the entire arrays in a highly optimized manner.

#For large-scale numerical computations, the performance benefits of NumPy arrays are substantial, making them the preferred choice for scientific computing and data analysis tasks in Python.

#Q7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.



#**np.vstack()**

##**Purpose:** Stacks arrays vertically (row-wise).
##**Behavior:**
##Joins arrays along the first axis (axis=0).
##Requires arrays to have the same number of columns.
#**np.hstack(**)

##**Purpose:** Stacks arrays horizontally (column-wise).
##**Behavior:**
##Joins arrays along the second axis (axis=1).
##Requires arrays to have the same number of rows.

#Example:

In [ ]:
import numpy as np

# Define arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Vertical stacking
vstack_result = np.vstack((arr1, arr2))
print("vstack:\n", vstack_result)

# Horizontal stacking
hstack_result = np.hstack((arr1, arr2))
print("hstack:\n", hstack_result)

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack:
 [[1 2 5 6]
 [3 4 7 8]]


#Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#`np.fliplr(arr)`

##**Purpose:** Flips the array in the left-right direction (horizontally).
##**Effect:**
##For 1D arrays: No effect (essentially a no-op).
##For 2D arrays: Reverses the order of columns.
##For higher-dimensional arrays: Reverses the order of elements along the second axis.
#`np.flipud(arr)`

##**Purpose:** Flips the array in the up-down direction (vertically).
##**Effect**:
##For 1D arrays: Reverses the order of elements.
##For 2D arrays: Reverses the order of rows.
##For higher-dimensional arrays: Reverses the order of elements along the first axis.

#**Q9.**Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?




#The `numpy.array_split()` function in NumPy splits an array into multiple sub-arrays.

#Key Functionality:

#Divides an array into sub-arrays:
##It divides the input array into a specified number of sub-arrays.
#Handles Uneven Splits:
##If the array cannot be evenly divided by the number of desired sub-arrays, array_split() distributes the extra elements intelligently.
##The first few sub-arrays may have one more element than the rest.

#**Q10.** Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#**Vectorization in NumPy:**
##Vectorization in NumPy refers to performing operations on entire arrays at once, rather than iterating over individual elements using Python loops.

##**Benefits:**
##1.Speed
##2.Conciseness
##3.Readability

##Example:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Vectorized addition
result1 = arr + 2  # Adds 2 to each element of the array

# Equivalent loop-based approach (slower)
result2 = []
for x in arr:
    result2.append(x + 2)

print(result1)
print(result2)

[3 4 5 6 7]
[3, 4, 5, 6, 7]


#**Broadcasting in NumPy**
##Broadcasting is a powerful mechanism in NumPy that allows operations between arrays of different shapes.

#**Rules:**
##NumPy attempts to automatically "broadcast" the smaller array to match the shape of the larger array.
##This is possible under certain conditions, such as when one array has dimensions of size 1 or when the dimensions of the arrays are compatible.
#**Benefits:**
#Simplifies operations between arrays of different shapes.
#Avoids the need to manually reshape or duplicate arrays to perform operations.
##Example:

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # (2, 3) shape
arr2 = np.array([1, 2, 3])  # (3,) shape

result = arr1 + arr2
print(result)

# Broadcasting allows the 1D array (arr2) to be "stretched"
# along the rows of the 2D array (arr1) before the addition.

[[2 4 6]
 [5 7 9]]


#**Practical Questions:**

#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [3]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = array.T

array, transposed_array


(array([[ 16,  67,  68],
        [ 76,  93, 100],
        [  3,  48,  42]]),
 array([[ 16,  76,   3],
        [ 67,  93,  48],
        [ 68, 100,  42]]))

#Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [4]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

array_1d, array_2x5, array_5x2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [8]:
import numpy as np

# Create a 4x4 NumPy array with random float values between 0 and 1
original_array = np.random.rand(4, 4)
print("Original 4x4 Array:\n", original_array)

# Create a 6x6 array filled with zeros
bordered_array = np.zeros((6, 6))

# Copy the original array into the center of the bordered array
bordered_array[1:-1, 1:-1] = original_array

print("\nBordered 6x6 Array:\n", bordered_array)



Original 4x4 Array:
 [[0.77646506 0.06599434 0.7507725  0.57561213]
 [0.01957601 0.77149708 0.29449159 0.14023958]
 [0.04434676 0.17490021 0.96133692 0.68768535]
 [0.05300607 0.05210605 0.13740162 0.31211487]]

Bordered 6x6 Array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.77646506 0.06599434 0.7507725  0.57561213 0.        ]
 [0.         0.01957601 0.77149708 0.29449159 0.14023958 0.        ]
 [0.         0.04434676 0.17490021 0.96133692 0.68768535 0.        ]
 [0.         0.05300607 0.05210605 0.13740162 0.31211487 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [9]:
import numpy as np

# Create an array of integers from 10 to 60 (inclusive) with a step of 5
arr = np.arange(10, 61, 5)

print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [16]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
print("Uppercase:", uppercase_array)

lowercase_array = np.char.lower(string_array)
print("Lowercase:", lowercase_array)

titlecase_array = np.char.title(string_array)
print("Title Case:", titlecase_array)

capitalize_array = np.char.capitalize(string_array)
print("Capitalize:", capitalize_array)

swapcase_array = np.char.swapcase(string_array)
print("Swapcase:", swapcase_array)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']
Swapcase: ['PYTHON' 'NUMPY' 'PANDAS']


#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [17]:
import numpy as np
# Generate a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character of every word in the array
spaced_array = np.char.join(' ', words_array)

words_array, spaced_array


(array(['hello', 'world', 'numpy'], dtype='<U5'),
 array(['h e l l o', 'w o r l d', 'n u m p y'], dtype='<U9'))

#Q7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [19]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Element-wise Addition:
[[ 6  8]
 [10 12]]

Element-wise Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Element-wise Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


#Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [21]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

identity_matrix, diagonal_elements


(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

#Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [22]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Define a function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Use vectorized filtering to find prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers Array:")
print(random_integers)
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[518 775 729 702 870 607 111 521 858 794 435 357 937 500 266 592 282 910
 862 614 693  86  94 987 372 244 780 456 473 683 171 477 916 592 194  12
 687 564 695  10 768 523 269  92  92 119 502 215 659 613 597 250 446 601
 172 372 855 790 220 370 922 295 610 135 686 964 494 887 864 780 974 897
 207 888 309 793 661 944 262 709 924 657 293 781  12 501 880 473 313 473
 859 878 755 940  47 844 975 738 452 803]

Prime Numbers in the Array:
[607, 521, 937, 683, 523, 269, 659, 613, 601, 887, 661, 709, 293, 313, 859, 47]


#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [24]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 40, size=30)  # Random temperatures between 20°C and 40°C

# Reshape the array into weeks (4 weeks, each with 7 days, and 2 remaining days)
weeks = daily_temperatures[:28].reshape(4, 7)  # Take the first 28 days for 4 weeks
extra_days = daily_temperatures[28:]  # Remaining days

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Calculate the average for the extra days (if any)
extra_days_average = np.mean(extra_days) if extra_days.size > 0 else None

# Display results
print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)
if extra_days_average is not None:
    print(f"\nAverage for Extra Days: {extra_days_average:.2f}°C")


Daily Temperatures for the Month:
[35 25 23 25 31 22 24 32 36 29 32 27 31 35 29 37 20 39 39 35 27 35 28 39
 35 33 31 31 38 22]

Weekly Averages:
[26.42857143 31.71428571 32.28571429 33.14285714]

Average for Extra Days: 30.00°C
